# Generated by Django 5.2.10 on 2026-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
